server:
  port: 8090
  forward-headers-strategy: native
  compression:
    enabled: false
spring:
  mvc:
    pathmatch:
      use-suffix-pattern: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    add-properties: false
  output:
    ansi:
      enabled: always
  datasource:
    # type: com.zaxxer.hikari.HikariDataSource
    type: com.mysql.cj.jdbc.MysqlDataSource

    # driver-class-name: org.h2.Driver # H2 database configuration.
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:h2:file:~/.halo/db/halo
    url: jdbc:mysql://127.0.0.1:3306/halo?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=UTC
    username: root
    password: lm13190492195
    # password: DB_mima~9749

  h2:
    console:
      settings:
        web-allow-others: false
      path: /h2-console
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
      location: /tmp/run.halo.app
management:
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: [ 'httptrace', 'metrics','env','logfile','health' ]
logging:
  level:
    run.halo.app: INFO
    org.eclipse.jetty.server.HttpChannel: ERROR
  file:
    path: ${user.home}/.halo/logs

springfox:
  documentation:
    enabled: false

halo:
  download-timeout: 5m
  cache: memory